# Form implementation generated from reading ui file 'kabinet.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kabinet(object):
    def setupUi(self, kabinet):
        kabinet.setObjectName("kabinet")
        kabinet.resize(598, 481)
        self.centralwidget = QtWidgets.QWidget(kabinet)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 0, 461, 151))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.exitkab = QtWidgets.QPushButton(self.centralwidget)
        self.exitkab.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.exitkab.setStyleSheet("background-color: #5555F5")
        self.exitkab.setObjectName("exitkab")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(100, 120, 381, 301))
        self.listWidget.setObjectName("listWidget")
        kabinet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kabinet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 598, 21))
        self.menubar.setObjectName("menubar")
        kabinet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kabinet)
        self.statusbar.setObjectName("statusbar")
        kabinet.setStatusBar(self.statusbar)

        self.retranslateUi(kabinet)
        QtCore.QMetaObject.connectSlotsByName(kabinet)

    def retranslateUi(self, kabinet):
        _translate = QtCore.QCoreApplication.translate
        kabinet.setWindowTitle(_translate("kabinet", "Личный кабинет"))
        self.label.setText(_translate("kabinet", "Вы успешно авторизовались!"))
        self.exitkab.setText(_translate("kabinet", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kabinet = QtWidgets.QMainWindow()
    ui = Ui_kabinet()
    ui.setupUi(kabinet)
    kabinet.show()
    sys.exit(app.exec())
