# Form implementation generated from reading ui file 'kabinet.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_kabinet(object):
    def setupUi(self, kabinet):
        kabinet.setObjectName("kabinet")
        kabinet.resize(611, 481)
        self.centralwidget = QtWidgets.QWidget(kabinet)
        self.centralwidget.setObjectName("centralwidget")
        self.exitkab = QtWidgets.QPushButton(self.centralwidget)
        self.exitkab.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.exitkab.setStyleSheet("background-color: #5555F5")
        self.exitkab.setObjectName("exitkab")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 50, 581, 341))
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setObjectName("home")
        self.labelkab = QtWidgets.QLabel(self.home)
        self.labelkab.setGeometry(QtCore.QRect(60, 80, 461, 151))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.labelkab.setFont(font)
        self.labelkab.setObjectName("labelkab")
        self.stackedWidget.addWidget(self.home)
        self.decypher_window = QtWidgets.QWidget()
        self.decypher_window.setObjectName("decypher_window")
        self.decypher_le = QtWidgets.QLineEdit(self.decypher_window)
        self.decypher_le.setGeometry(QtCore.QRect(40, 80, 521, 61))
        self.decypher_le.setObjectName("decypher_le")
        self.decypher_btn = QtWidgets.QPushButton(self.decypher_window)
        self.decypher_btn.setGeometry(QtCore.QRect(210, 230, 161, 61))
        self.decypher_btn.setObjectName("decypher_btn")
        self.stackedWidget.addWidget(self.decypher_window)
        self.cypher_window = QtWidgets.QWidget()
        self.cypher_window.setObjectName("cypher_window")
        self.cypher_btn = QtWidgets.QPushButton(self.cypher_window)
        self.cypher_btn.setGeometry(QtCore.QRect(210, 230, 161, 61))
        self.cypher_btn.setObjectName("cypher_btn")
        self.cypher_le = QtWidgets.QLineEdit(self.cypher_window)
        self.cypher_le.setGeometry(QtCore.QRect(40, 80, 521, 61))
        self.cypher_le.setObjectName("cypher_le")
        self.stackedWidget.addWidget(self.cypher_window)
        self.kabcyph = QtWidgets.QPushButton(self.centralwidget)
        self.kabcyph.setGeometry(QtCore.QRect(70, 400, 161, 31))
        self.kabcyph.setObjectName("kabcyph")
        self.kabdecyph = QtWidgets.QPushButton(self.centralwidget)
        self.kabdecyph.setGeometry(QtCore.QRect(370, 400, 161, 31))
        self.kabdecyph.setObjectName("kabdecyph")
        kabinet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kabinet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        kabinet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kabinet)
        self.statusbar.setObjectName("statusbar")
        kabinet.setStatusBar(self.statusbar)

        self.retranslateUi(kabinet)
        QtCore.QMetaObject.connectSlotsByName(kabinet)

    def retranslateUi(self, kabinet):
        _translate = QtCore.QCoreApplication.translate
        kabinet.setWindowTitle(_translate("kabinet", "Личный кабинет"))
        self.exitkab.setText(_translate("kabinet", "Выйти"))
        self.labelkab.setText(_translate("kabinet", "Выберите нужное вам окно"))
        self.decypher_btn.setText(_translate("kabinet", "Расшифровать"))
        self.cypher_btn.setText(_translate("kabinet", "Зашифровать"))
        self.kabcyph.setText(_translate("kabinet", "Окно шифрования"))
        self.kabdecyph.setText(_translate("kabinet", "Окно расшифрования"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kabinet = QtWidgets.QMainWindow()
    ui = Ui_kabinet()
    ui.setupUi(kabinet)
    kabinet.show()
    sys.exit(app.exec())
